Sprint56
borisbbtest/ya-dr pull request #2
Opened 2022-08-13 02:55 UTC by borisbbtest

2022-08-15 19:30 UTC, sergeysergeevru requested changes
Привет) В общем код хороший и поделен правильно. Основные проблемы: дубликация кода, отсутсвие атомарности в списании баланса, хранение пароля в открытом виде, перегруженная имплементация при работе с базой. В общем комменты оставил. Не уверен что будет время, но в будущем можно еще тестами дополнить.  Спасибо!)

2022-08-15 19:30 UTC, sergeysergeevru commented on cmd/gophermart/main.go
> +		}
не факт что создавать дефолный кофиг при неудачном чтении хорошее решение: вообще если конфиг не удалось считать, то можно спокойно класть приложение, иначе если это произойдет в проде, может получиться, что приложение стартануло не там и не с теми настройками.

2022-08-15 19:30 UTC, sergeysergeevru commented on cmd/gophermart/main.go
> +var log = logrus.WithField("context", "main")
непонятно преимущество глобальное переменной, когда она используется в 1 месте.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/config/server_conf.go
> +}
можно сократить функцию в несколько раз :) Например:
```go
type MainConfig struct {
	AccrualSystemAddress string `yaml:"ACCRUAL_SYSTEM_ADDRESS" env:"ACCRUAL_SYSTEM_ADDRESS"`
}

func GetConfig() (config *MainConfig, err error) {
     cfg := &MainConfig{}
     // допустим здесь чтение и натягивание yaml. 
     // ничего интересного, поэтому пропускаю этот момент
     err := env.Parse(cfg)
     if err != nil {
             return nil, fmt.Errorf("can not read env variables: %w",  err)  
    }
    flag.StringVarP(&cfg.AccrualSystemAddress, "accrual_system_adders", "r", cfg.AccrualSystemAddress, "Accrual system address")
/// для остальных полей аналогично
   return cfg, nil
}


```

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/config/server_conf.go
> +	} else {
вероятно здесь мы можем вернуть уже ошибку выше: если невозможно отпарсить конфиг по окружению, значит что-то не то происходить

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/config/server_conf.go
> +	} else {
и тогда можно убрать ветвление с else

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_filesever.go
> +	}
копипаста с доки, но все же я предпочел бы вернуть ошибку выше)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +	}
это можно со спокойно душой в middleware уносить, не самая лучшая идея копипастить: если придется поддерживать еще один алгоритм сжатия то тебе придется идти и руками править все нужные места. если будет в middleware, то только в одном

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		log.Errorf("error decoding message: %v", err)
ты используешь logrus, я думаю удобнее будет сделать одну строчку лога, но с несколькими полями

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		log.Fatalln(err)
фатал завершит приложение https://pkg.go.dev/github.com/sirupsen/logrus#Fatalln Не думаю, что ронять приложения на эту ошибку хорошая идея, мне кажется мы можем продолжать работу. Просто отдать 500 клиенту.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		time, _ := tools.AddCookie(w, r, tools.AuthCookieKey, str, 30*time.Minute)
все ошибки должны быть валидированы https://github.com/golang/go/wiki/CodeReviewComments#handle-errors
для 69 строчки особенно важно: не смогли поставить куку - процесс логина точно неудачно закончился

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		hook.Session.DBSession[str] = user
Я не копилятор, но на конкуретном доступе к мапе получишь ошибку :)
https://go.dev/play/p/DZcIdCmMCkg
![image](https://user-images.githubusercontent.com/12248824/184687083-bff9983d-a436-43c3-9a76-02f7438d4033.png)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +	}
можно убрать лишнее ветвление
```suggestion
		w.WriteHeader(http.StatusOK)
		return
	} 
	w.WriteHeader(http.StatusUnauthorized)

```

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		w.WriteHeader(http.StatusUnauthorized)
ставим здесь `return` ибо дальнейшее выполнение бессмысленно

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +	"github.com/borisbbtest/ya-dr/internal/tools"
Я бы посоветовал не называть так пакеты: константы/переменные/пакеты и т.д. и т.п. должны отражать смысл и несущий функционал достаточно четко. Основной смысл всего этого в том, чтобы любой разработчик пришедший на помощь или принимающий проект смог быстрее начать ориентироваться в коде. https://go.dev/blog/package-names

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +	"github.com/borisbbtest/ya-dr/internal/tools"
в общем tools слабо отражает подноготную

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handlers_register.go
> +		hook.Session.DBSession[str] = m
копипаста с логина, думаю можно в отдельный метод хендлеров унести

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handlers_register.go
> +	user, _ := hook.Storage.PutUser(m)
проверка ошибки как писал важна. Но тут гораздо круче проблема: запись пароля в базу в открытом виде. Теперь любая компроментация  db такое раздолье даст злоумышленнику. Давай хотя бы какой нибудь простой крипто приметив применим в виде хеша, а лучше с солью, а еще лучше brypt, scrypt и тому подобное)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/tools/cookie.go
> +		cookie, _ := r.Cookie(AuthCookieKey)
проверка ошибки: общем не буду дублировать, пробегись везде и добавь проверки

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/tools/cookie.go
> +package tools
про название пакетов тоже уже писал) в принципе данный файл навряд ли будет использовать дальше хендлеров, можно его туда и унести вероятно

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/tools/genkey.go
> +func GenerateKeyGen(initialLink string) string {
функция вроде нигде не используется

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/tools/genkey.go
> +	src := []byte("Ключ от сердца")
<3

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/tools/genkey.go
> +		os.Exit(1)
если GenerateKeyGen нигде не используется, то данный метод тоже не нужОн))) Собтвенно я бы предпочел ошибку выше отдавать, не факт что глушить приложение нужно.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_get_orders.go
> +	})
я думаю можно просто сделать sort by в SQL, если будешь прикручивать пагинацию в будущем, то данная сортировка тебе ничего не даст. Не будешь же ты вытаскивать все записи, чтобы отсортировать и вернуть клиенту только кусок)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_get_orders.go
> +		log.Info(err)
еще 500 надо клиенту вернуть, это точно косяк сервера, 200 тут не уместна

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_get_withdrawals.go
> +	})
аналогично другому слайсу)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_get_withdrawals.go
> +		log.Info(err)
500)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_tools.go
> +		}
вот этот кусок просится уехать в отдельный клиент (дата провайдер или другое угодное название)) )
Что-нибудь с интерфейсом:
```go
type AccrualDataProvider interface {
        GetByID(oderNumber string) (*model.DataOrder, error)
}
```
Допустим в будущем мы запустим новый аккруал на grpc или, не дай бог, на soap. Ну или в aws лябмду унесем, тогда просто напишем новый клиент и подменим через dependency injection. А еще можно мок тесты писать) Ох как много применений)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_tools.go
> +				})
если UpdateBalance вернет ошибку и запись в базе не обновится, то горутина завершится на 63 строке, и больше мы никогда не сможем пополнить твой баланс (в рамках этого решения). Будет дико неудобно службе поддержке объяснять, почему мы не начислили баллы за заказ)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_set_order.go
> +	go hook.calculateLoyaltySystem(orderNumber, currentPerson)
довольно проблематичное решение:
1. если какая-то проблема произойдет с accrual (проблемы с доступностью или просто перестанет обсчитывать заказы), то горутины так и будут висеть до второго пришествия)
2. если приложение упадет, то после перезапуска старые необработанные заказы не будут обработаны.

Если тебе интересно мое мнение, то я бы предпочел иметь вокер на фоне, который будет выгружать из базы заказы и пытаться их обработать по расписанию. Самое прямолинейное и отказоустойчивое решение. Но можно придумать и что-то еще круче. Но для mvp этого обычно точно достаточно

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_set_withdraw.go
> +	currentaccrual := m.Sum * -1.0
```suggestion
	currentaccrual := -m.Sum
```

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_set_withdraw.go
> +	currentaccrual := m.Sum * -1.0
если есть сомнения. https://go.dev/play/p/v5PYy0aEjHB

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/handlers/handler_set_withdraw.go
> +	}
должно выполняться атомарно, то есть в рамках одной транзакции. Любой пользователь владеющий питоном сможет оплатить себе больше заказов на сумму большую чем баланс. Собственно представь что одновременно отправляешь запрос на списание двух разных заказов. Если оба запроса выполнят GetBalance раньше чем один из них сделает  UpdateBalance, то мы некорректно обработаем запросы. И сделаем некорректные списания.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/middleware/middleware_gzip.go
> +}
так а почему не используешь имплементацию?  все же есть, а мы таскаем копипасты(((

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/postgres/handlers_init_table.go
> +}
я бы предпочел сделать полноценные миграции. Например, можно goose использовать. С текущем подходом менять схему базы в проде будет проблематично.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/postgres/handlers_init_table.go
> +						"Person" "text" NOT NULL,
Лучше добавить id в таблицу с юзерами и через него ссылаться. Ибо если/когда прийдет к нам менеджер и скажет: "повелеваю: дайте возможность пользователю менять логин", то придется либо костылить или сделать так как я изначально предложил)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +	pgp     postgres.Plugin
непонятна затея с этим плагином, обычно одного коннекта к базе или pgx.Pool какая-то еще надстройка сверху явно оверинжиниринг

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +	res, err := hook.pgp.NewDBConn("pgsql.insert.tb.order", []string{}, hook.connStr, buff)
тяжело поддерживаемый подход: чтобы создать новый метод хранилища, то приходится писать в нескольких местах: описывать метод стораджа, а потом еще идти плагин менять. ИМХО прямолинейно сделать примерно так будет удобнее поддерживать и читать. При этом текущий вариант с плагином не дает преимуществ. В моем видении сторадж должен выглядеть примерно так, как минимум когда мы пилим mvp и не можем еще отпрофилировать где и что у нас западает:
```go
type SomeStorage struct { 
     pool *pgx.Pool
}
func New(pool *pgx.Pool) *SomeStorage { // можем создать коннект выше и передать сюда, тогда можно вызывать pool.Close() прямо в мейн пакете. 
    return &SomeStorage{pool:pool}
} 

const inserQuery = `INSERT INTO users (message)
VALUES ($1)
RETURNING id`

// let's image we have the next structure in models:
// type Item struct {
//     ID int64
//     Message string
// }

func (s SomeStorage) CreateItem(item *models.Item) error {
        err := s.pool. QueryRow(inserQuery, item.Message).Scan(&item.ID)
        return err
}
```
в общем у меня такое видение на репо обычно

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +	res, err := hook.pgp.NewDBConn("pgsql.insert.tb.order", []string{}, hook.connStr, buff)
возможно где-то косяк в синтаксисе, так как пишу по памяти, но смысл я думаю понятен. Не стоит делить на слои когда для этого нет обосновании. Здесь же (в текущей имплементации) все очень жестко связано и гибкости никакой не приносит. Стораджы обычно максимально простые должны получаться: только сохранять и извлекать информацию из баз, ну еще натягивать данные на структуры. В общем все.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/postgres/handlers_update_order.go
> +}
давай на примере этого метода рассмотрим: смотри чтобы имплементировать метод `func (hook *StoreDBinPostgreSQL) UpdateOrder(v *model.DataOrder) (string, error)` пришлось (помимо реализации UpdateOrder в StoreDBinPostgreSQL)  еще добавить константу, расширить NewDBConn и написать текущий метод. А можно просто сделать StoreDBinPostgreSQL.UpdateOrder метод, который будет по сути тоже самое что и updateOrderHandler. Keep it simple ;)

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +	pgp     postgres.Plugin
Ааа, я кажется разобрался в твоем плагине. Если я правильно понял, то ты предполагаешь инкапсулировать туда коннекты к разным базам или с разными кредами. Не могу придумать место, где это будет объективно полезным внедрением. Особенно когда приходится каждый раз передавать к какой базе стоит подключаться.

2022-08-15 19:30 UTC, sergeysergeevru commented on internal/postgres/conn.go
> +	}
вот это прикольно, можно будет оставить, только без общих оберток и просто прокидывать newConn в имплементацию стораджа :)

2022-08-16 04:51 UTC, borisbbtest commented on internal/postgres/handlers_init_table.go
> +						"Person" "text" NOT NULL,
готово

2022-08-16 04:53 UTC, borisbbtest commented on cmd/gophermart/main.go
> +		}
Готово

2022-08-16 05:41 UTC, borisbbtest commented on internal/config/server_conf.go
> +}
поправил

2022-08-16 05:50 UTC, borisbbtest commented on internal/config/server_conf.go
> +	} else {
готово

2022-08-16 05:52 UTC, borisbbtest commented on internal/handlers/handler_filesever.go
> +	}
Это не основной фунционал

2022-08-16 06:40 UTC, borisbbtest commented on internal/handlers/handler_login.go
> +		time, _ := tools.AddCookie(w, r, tools.AuthCookieKey, str, 30*time.Minute)
Готово

2022-08-16 06:47 UTC, borisbbtest commented on internal/handlers/handler_login.go
> +		hook.Session.DBSession[str] = user
Запомнил поправлю только пойму как

2022-08-16 06:49 UTC, borisbbtest commented on internal/handlers/handler_login.go
> +	}
Поправил

2022-08-16 06:49 UTC, borisbbtest commented on internal/handlers/handler_login.go
> +		w.WriteHeader(http.StatusUnauthorized)
поправил

2022-08-16 06:50 UTC, borisbbtest commented on internal/handlers/handler_login.go
> +	"github.com/borisbbtest/ya-dr/internal/tools"
Заполнил учту

2022-08-16 07:25 UTC, borisbbtest commented on internal/handlers/handlers_register.go
> +	user, _ := hook.Storage.PutUser(m)
поправил

2022-08-16 08:05 UTC, borisbbtest commented on internal/handlers/handler_tools.go
> +		}
подумаю на будущие ,  не успею сделать

2022-08-16 08:05 UTC, borisbbtest commented on internal/handlers/handler_set_order.go
> +	go hook.calculateLoyaltySystem(orderNumber, currentPerson)
Это я записал ! Нужно подумать

2022-08-16 08:57 UTC, borisbbtest commented on internal/postgres/handlers_init_table.go
> +}
не успею внизу еще чЕто много проблем

2022-08-17 14:07 UTC, sergeysergeevru approved these changes
Привет) Хорошо! Видел что не все успеваешь поправить, работу принимаю, надеюсь комменты были полезны. Спасибо!

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/tools/genkey.go
> +		fmt.Printf("error: %v\n", err)
чего-то в прошлый раз не обратил внимание.  Удобнее логировать через log: он пишет время и можно проще подменить на другой логгер совместимый с "log", например

`import (
// bla bla bla
       log "github.com/sirupsen/logrus"
)`

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +					COMMENT ON TABLE public."Balance"  IS 'This table was created for storage data about Balance';
если/когда в прод пойдешь то стоит полноценные миграция сделать, например заюзать библиотеку goose. Так будет проще расширять схему DB при выкате новых фич.

2022-08-17 14:07 UTC, sergeysergeevru commented on cmd/gophermart/main.go
> +		return
стоит ошибку залогировать, а то если приложение просто не запустилось придется в код лезть чтобы понимать причины

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/handlers/handler_set_withdraw.go
> +	currentMutex.Unlock()
скоре всего надо на defer ставить после 53 строки. Иначе если вылетит ошибка, то лок и будет висеть

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/handlers/handler_set_withdraw.go
> +	currentMutex.Lock()
как подход может быть. Надо только понимать, что в случае если придется горизонтально масштабироваться, то надо будет применять распределенный лок (например, на основе редиса или другого обитателя зоопарка баз данных)) ) либо уйти в сторону транзакций в БД. В текущем варианте второе смотрится более предпочтительно. Но распределенный лок тоже ок.

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/handlers/handler_get_balance.go
> +		log.Error("GetJSONBalanceHandler - ", err)
вроде норм было, отдавали пользователю ошибку. Если не смогли выгрузить данные из базы, то статус ОК здесь неуместен

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/handlers/handler_login.go
> +		hook.Session.DBSession[str] = user
для понимания здесь и сейчас нужен мьютекс. Но вообще бы само хранилище сессий стоит унести в некоторую абстракцию с методами положить и взять в/из хранилища. А там уже для мапы можно мьютксы вешать или со временем заменить мапу, на использование редиса.

2022-08-17 14:07 UTC, sergeysergeevru commented on internal/storage/storedbpg.go
> +	conn, err := res.pgp.NewConn()
можно было бы сразу здесь делать коннект, например,
`pgxpool.ConnectConfig(context.Background(), config)` и закинуть в StoreDBinPostgreSQL и все, его можно переиспользовать, без каких либо проблем)

2022-09-15 22:50 UTC, merged